<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="APT04-1DKF7G3" failures="1" tests="3" name="ErrorValidation" time="18.601" errors="0" timestamp="2024-04-11T10:27:36 IST">
  <testcase classname="BhanuFrameworkPractice.FrameworkTest.ErrorValidation" name="fourthTest" time="0.774"/>
  <testcase classname="BhanuFrameworkPractice.FrameworkTest.ErrorValidation" name="secondTest" time="0.961">
    <skipped/>
  </testcase> <!-- secondTest -->
  <testcase classname="BhanuFrameworkPractice.FrameworkTest.ErrorValidation" name="secondTest" time="0.691">
    <failure type="java.lang.AssertionError" message="expected [ sadfaceUsername and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [ sadfaceUsername and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at BhanuFrameworkPractice.FrameworkTest.ErrorValidation.secondTest(ErrorValidation.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- secondTest -->
</testsuite> <!-- ErrorValidation -->
